image: node:14

stages:
  - Test
  - Code quality
  - Build
  - Deploy

before_script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - apt-get update -qy
  - apt-get install -y google-chrome-stable
  - npm install

Unit test:
  stage: Test
  script:
    - echo "Running unit tests..."
    - npm run test -- --browsers ChromeHeadlessNoSandbox

Eslint:
  stage: Code quality
  script:
    - echo "Linting code... This will take about 10 seconds."
    - npm run lint

Npm audit:
  stage: Code quality
  allow_failure: true
  script:
    - echo "Running npm packages audit..."
    - npm audit

Build:
  stage: Build
  script:
    - echo "Building the app..."
    - npm run build

Staging deploy:
  stage: Deploy
  script:
    - echo "Deploying to staging..."
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_REGION=$AWS_REGION
    - aws elasticbeanstalk create-application-version --application-name $EB_ENVIRONMENT_NAME --version-label $CI_COMMIT_REF_NAME --source-bundle S3Bucket=$S3_BUCKET_NAME,S3Key=$CI_COMMIT_REF_NAME
    - aws elasticbeanstalk update-environment --application-name $EB_ENVIRONMENT_NAME --environment-name $EB_ENVIRONMENT_NAME --version-label $CI_COMMIT_REF_NAME
  when: manual
