name: release-please
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2

        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          release-type: simple
